channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=24.0
- pip:
  - mlflow==2.10.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.12.0
  - typing-extensions==4.9.0
name: mlflow-env
